import {
  AppState,
  Goal,
  RoadmapTopic,
  Semester,
  StudySession,
  Subject,
  TimeBlock,
  TimetableSlot,
  UserProfile,
} from '../types';

export const SEED_PROFILE: UserProfile = {
  name: 'Alex Mercer',
  university: 'State Polytechnic University',
  degreeMajor: 'Computer Science & Software Engineering',
  currentYear: 'Year 3 (Junior)',
  dailyCapacityMaxHours: 4.5,
  defaultBufferMinutes: 15,
  sleepHours: 8,
  travelTimeMinutes: 30,
  wakeTime: '07:30',
  sleepTime: '23:30',
  currentSkills: ['C / C++', 'Python', 'Data Structures', 'Git & Linux Shell', 'SQL'],
  careerInterests: ['Operating Systems & Kernel Engineering', 'High-Performance Distributed Systems'],
  currentProjects: ['POSIX Multithreaded Job Worker', 'LSM-Tree Key-Value Store'],
  aiProvider: 'offline',
  hasCompletedOnboarding: true,
};

export const SEED_SEMESTERS: Semester[] = [
  {
    id: 'sem-fall-2026',
    name: 'Fall 2026 (Semester 5)',
    startDate: '2026-09-01',
    endDate: '2026-12-20',
    expectedEndDate: '2026-12-20',
    actualEndDate: undefined,
    targetWeeklyStudyHours: 18,
    isActive: true,
    holidays: [
      {
        id: 'h-1',
        name: 'Mid-Semester Reading Week',
        startDate: '2026-10-18',
        endDate: '2026-10-25',
        type: 'break',
      },
      {
        id: 'h-2',
        name: 'Thanksgiving Break',
        startDate: '2026-11-25',
        endDate: '2026-11-29',
        type: 'holiday',
      },
    ],
  },
];

export const SEED_SUBJECTS: Subject[] = [
  {
    id: 'sub-os',
    semesterId: 'sem-fall-2026',
    code: 'CS 301',
    name: 'Operating Systems & Concurrency',
    color: '#3B82F6', // Blue
    targetWeeklyHours: 6,
    credits: 4,
    syllabusOverview: 'Process synchronization, memory management, virtual memory, scheduling algorithms, and file systems.',
  },
  {
    id: 'sub-algo',
    semesterId: 'sem-fall-2026',
    code: 'CS 312',
    name: 'Advanced Algorithms & Complexity',
    color: '#10B981', // Emerald
    targetWeeklyHours: 5,
    credits: 4,
    syllabusOverview: 'Dynamic programming, graph algorithms (Dijkstra, Bellman-Ford), network flow, NP-completeness.',
  },
  {
    id: 'sub-db',
    semesterId: 'sem-fall-2026',
    code: 'CS 340',
    name: 'Database Architecture & Systems',
    color: '#8B5CF6', // Purple
    targetWeeklyHours: 4,
    credits: 3,
    syllabusOverview: 'Relational algebra, B-trees, indexing, ACID transactions, WAL logging, and query optimization.',
  },
  {
    id: 'sub-stats',
    semesterId: 'sem-fall-2026',
    code: 'MATH 280',
    name: 'Probability & Engineering Stats',
    color: '#F59E0B', // Amber
    targetWeeklyHours: 3,
    credits: 3,
    syllabusOverview: 'Discrete & continuous distributions, Bayesian inference, hypothesis testing, Markov chains.',
  },
];

export const SEED_TIMETABLE: TimetableSlot[] = [
  // Monday
  {
    id: 'tt-1',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-os',
    title: 'CS 301: OS Lecture',
    dayOfWeek: 'monday',
    startTime: '09:00',
    endTime: '10:30',
    location: 'Engineering Hall 104',
    isFixed: true,
    type: 'lecture',
  },
  {
    id: 'tt-2',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-algo',
    title: 'CS 312: Algorithms Lecture',
    dayOfWeek: 'monday',
    startTime: '11:00',
    endTime: '12:30',
    location: 'Science Center 202',
    isFixed: true,
    type: 'lecture',
  },
  {
    id: 'tt-3',
    semesterId: 'sem-fall-2026',
    title: 'Commute & Campus Transit',
    dayOfWeek: 'monday',
    startTime: '08:15',
    endTime: '08:45',
    isFixed: true,
    type: 'commute',
  },

  // Tuesday
  {
    id: 'tt-4',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-db',
    title: 'CS 340: Database Systems',
    dayOfWeek: 'tuesday',
    startTime: '10:00',
    endTime: '11:30',
    location: 'Engineering Hall 210',
    isFixed: true,
    type: 'lecture',
  },
  {
    id: 'tt-5',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-os',
    title: 'CS 301: OS Systems Lab',
    dayOfWeek: 'tuesday',
    startTime: '14:00',
    endTime: '16:00',
    location: 'Turing Computing Lab 3',
    isFixed: true,
    type: 'lab',
  },

  // Wednesday
  {
    id: 'tt-6',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-os',
    title: 'CS 301: OS Lecture',
    dayOfWeek: 'wednesday',
    startTime: '09:00',
    endTime: '10:30',
    location: 'Engineering Hall 104',
    isFixed: true,
    type: 'lecture',
  },
  {
    id: 'tt-7',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-stats',
    title: 'MATH 280: Probability Lecture',
    dayOfWeek: 'wednesday',
    startTime: '13:00',
    endTime: '14:30',
    location: 'Mathematics Hall 301',
    isFixed: true,
    type: 'lecture',
  },

  // Thursday
  {
    id: 'tt-8',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-algo',
    title: 'CS 312: Algorithms Tutorial & Problem Set',
    dayOfWeek: 'thursday',
    startTime: '11:00',
    endTime: '12:30',
    location: 'Science Center 105',
    isFixed: true,
    type: 'tutorial',
  },
  {
    id: 'tt-9',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-db',
    title: 'CS 340: SQL & Query Optimization Lab',
    dayOfWeek: 'thursday',
    startTime: '14:00',
    endTime: '15:30',
    location: 'Turing Computing Lab 1',
    isFixed: true,
    type: 'lab',
  },

  // Friday
  {
    id: 'tt-10',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-stats',
    title: 'MATH 280: Statistics Problem Session',
    dayOfWeek: 'friday',
    startTime: '10:00',
    endTime: '11:30',
    location: 'Mathematics Hall 301',
    isFixed: true,
    type: 'tutorial',
  },
];

export const SEED_TOPICS: RoadmapTopic[] = [
  // OS Topics (Forming a valid Directed Acyclic Graph)
  {
    id: 'top-os-1',
    subjectId: 'sub-os',
    title: 'Processes, Threads & PCB Anatomy',
    description: 'Process control blocks, context switching overhead, thread states, POSIX threads.',
    estimatedMinutes: 45,
    prerequisiteTopicIds: [],
    status: 'completed',
    masteryLevel: 100,
    orderIndex: 1,
    lastStudiedAt: '2026-09-18T14:30:00Z',
    notes: 'Mastered fork(), wait(), exec() mechanics and PCB structures.',
  },
  {
    id: 'top-os-2',
    subjectId: 'sub-os',
    title: 'CPU Scheduling Algorithms',
    description: 'Preemptive vs non-preemptive scheduling: FCFS, SJF, Round Robin, Multilevel Feedback Queues.',
    estimatedMinutes: 50,
    prerequisiteTopicIds: ['top-os-1'],
    status: 'completed',
    masteryLevel: 95,
    orderIndex: 2,
    lastStudiedAt: '2026-09-19T10:15:00Z',
    notes: 'RR time quantum tradeoffs thoroughly evaluated.',
  },
  {
    id: 'top-os-3',
    subjectId: 'sub-os',
    title: 'Race Conditions, Mutexes & Semaphores',
    description: 'Critical section problem, Peterson algorithm, counting vs binary semaphores, deadlock avoidance.',
    estimatedMinutes: 60,
    prerequisiteTopicIds: ['top-os-1'],
    status: 'in_progress',
    masteryLevel: 65,
    orderIndex: 3,
    lastStudiedAt: '2026-09-20T16:00:00Z',
    notes: 'Need to review deadlock Coffman conditions and banker algorithm.',
  },
  {
    id: 'top-os-4',
    subjectId: 'sub-os',
    title: 'Virtual Memory & Page Replacement',
    description: 'Paging, TLB hits/misses, multi-level page tables, LRU, Clock, Belady anomaly.',
    estimatedMinutes: 60,
    prerequisiteTopicIds: ['top-os-2', 'top-os-3'],
    status: 'ready',
    masteryLevel: 25,
    orderIndex: 4,
    notes: 'Prerequisites cleared; ready for deep focus block.',
  },
  {
    id: 'top-os-5',
    subjectId: 'sub-os',
    title: 'File Systems & Inode Layouts',
    description: 'VFS abstractions, ext4 inode layout, direct/indirect blocks, journaling and crash recovery.',
    estimatedMinutes: 55,
    prerequisiteTopicIds: ['top-os-4'],
    status: 'locked',
    masteryLevel: 0,
    orderIndex: 5,
  },

  // Algorithms Topics (Forming a valid DAG)
  {
    id: 'top-algo-1',
    subjectId: 'sub-algo',
    title: 'Asymptotic Analysis & Recurrences',
    description: 'Master Theorem, recursion trees, substitution method, big-O, big-Omega, big-Theta.',
    estimatedMinutes: 45,
    prerequisiteTopicIds: [],
    status: 'completed',
    masteryLevel: 100,
    orderIndex: 1,
    lastStudiedAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'top-algo-2',
    subjectId: 'sub-algo',
    title: 'Graph Traversal & DAG Topo-Sort',
    description: 'DFS timestamps, BFS shortest unweighted paths, topological sorting algorithms, cycle detection.',
    estimatedMinutes: 50,
    prerequisiteTopicIds: ['top-algo-1'],
    status: 'completed',
    masteryLevel: 90,
    orderIndex: 2,
    lastStudiedAt: '2026-09-17T15:00:00Z',
  },
  {
    id: 'top-algo-3',
    subjectId: 'sub-algo',
    title: 'Shortest Paths (Dijkstra & Bellman-Ford)',
    description: 'Greedy shortest paths, negative weight edges detection, priority queue optimizations.',
    estimatedMinutes: 60,
    prerequisiteTopicIds: ['top-algo-2'],
    status: 'in_progress',
    masteryLevel: 70,
    orderIndex: 3,
    lastStudiedAt: '2026-09-20T11:30:00Z',
  },
  {
    id: 'top-algo-4',
    subjectId: 'sub-algo',
    title: 'Dynamic Programming Formulations',
    description: 'Optimal substructure, overlapping subproblems, memoization vs bottom-up tabulation.',
    estimatedMinutes: 75,
    prerequisiteTopicIds: ['top-algo-1'],
    status: 'ready',
    masteryLevel: 40,
    orderIndex: 4,
  },
  {
    id: 'top-algo-5',
    subjectId: 'sub-algo',
    title: 'Network Flow & Ford-Fulkerson',
    description: 'Residual graphs, augmenting paths, Max-Flow Min-Cut theorem, Edmonds-Karp bounds.',
    estimatedMinutes: 60,
    prerequisiteTopicIds: ['top-algo-3'],
    status: 'locked',
    masteryLevel: 0,
    orderIndex: 5,
  },

  // Databases Topics
  {
    id: 'top-db-1',
    subjectId: 'sub-db',
    title: 'Relational Model & Extended Algebra',
    description: 'Tuple relational calculus, relational algebra operations (projection, selection, joins).',
    estimatedMinutes: 45,
    prerequisiteTopicIds: [],
    status: 'completed',
    masteryLevel: 95,
    orderIndex: 1,
    lastStudiedAt: '2026-09-16T14:00:00Z',
  },
  {
    id: 'top-db-2',
    subjectId: 'sub-db',
    title: 'B+ Tree Indexing & Hash Indices',
    description: 'Page layout, search and insert splitting algorithms, composite index ordering, clustered indices.',
    estimatedMinutes: 55,
    prerequisiteTopicIds: ['top-db-1'],
    status: 'ready',
    masteryLevel: 30,
    orderIndex: 2,
  },
  {
    id: 'top-db-3',
    subjectId: 'sub-db',
    title: 'ACID Transactions & Concurrency Control',
    description: 'Strict 2PL, conflict serializability, dependency graphs, phantom reads, MVCC.',
    estimatedMinutes: 60,
    prerequisiteTopicIds: ['top-db-2'],
    status: 'locked',
    masteryLevel: 0,
    orderIndex: 3,
  },

  // Statistics Topics
  {
    id: 'top-stats-1',
    subjectId: 'sub-stats',
    title: 'Discrete Probability & Axioms',
    description: 'Kolmogorov axioms, conditional probability, Bayes theorem, independence.',
    estimatedMinutes: 40,
    prerequisiteTopicIds: [],
    status: 'completed',
    masteryLevel: 90,
    orderIndex: 1,
    lastStudiedAt: '2026-09-17T09:00:00Z',
  },
  {
    id: 'top-stats-2',
    subjectId: 'sub-stats',
    title: 'Continuous Distributions & Central Limit Theorem',
    description: 'PDF/CDF properties, Normal, Exponential, Chi-square distributions, law of large numbers, CLT.',
    estimatedMinutes: 50,
    prerequisiteTopicIds: ['top-stats-1'],
    status: 'ready',
    masteryLevel: 35,
    orderIndex: 2,
  },
];

export const SEED_SESSIONS: StudySession[] = [
  {
    id: 'sess-1',
    subjectId: 'sub-os',
    topicId: 'top-os-1',
    startTime: '2026-09-18T14:00:00Z',
    endTime: '2026-09-18T14:45:00Z',
    plannedDurationMinutes: 45,
    actualDurationMinutes: 45,
    comprehensionRating: 5,
    energyRating: 4,
    keyTakeaways: 'PCB memory layout and register preservation across hardware interrupts.',
    date: '2026-09-18',
  },
  {
    id: 'sess-2',
    subjectId: 'sub-algo',
    topicId: 'top-algo-2',
    startTime: '2026-09-19T10:00:00Z',
    endTime: '2026-09-19T10:50:00Z',
    plannedDurationMinutes: 45,
    actualDurationMinutes: 50,
    comprehensionRating: 4,
    energyRating: 4,
    keyTakeaways: 'DFS start/finish timestamp theorem for detecting back-edges in directed graphs.',
    date: '2026-09-19',
  },
  {
    id: 'sess-3',
    subjectId: 'sub-os',
    topicId: 'top-os-3',
    startTime: '2026-09-20T16:00:00Z',
    endTime: '2026-09-20T16:55:00Z',
    plannedDurationMinutes: 50,
    actualDurationMinutes: 55,
    comprehensionRating: 3,
    energyRating: 3,
    keyTakeaways: 'Semaphores eliminate busy waiting by placing blocked tasks on a wait queue.',
    date: '2026-09-20',
  },
];

export const SEED_GOALS: Goal[] = [
  {
    id: 'goal-1',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-os',
    title: 'Master Operating Systems Core Primitives',
    description: 'Achieve 85%+ mastery across all synchronization, memory, and kernel topics.',
    targetValue: 85,
    currentValue: 65,
    unit: '%',
    horizon: 'semester',
    deadline: '2026-12-15',
    status: 'active',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'goal-2',
    semesterId: 'sem-fall-2026',
    subjectId: 'sub-algo',
    title: 'Complete 25 Graph & Dynamic Programming Problems',
    description: 'Implement key algorithms in C++ from scratch and benchmark asymptotic runtime.',
    targetValue: 25,
    currentValue: 14,
    unit: 'problems',
    horizon: 'monthly',
    deadline: '2026-10-15',
    status: 'active',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'goal-3',
    semesterId: 'sem-fall-2026',
    title: 'Weekly Study Discipline Ceiling',
    description: 'Log at least 16 productive study hours without exceeding the 4.5h daily safety threshold.',
    targetValue: 18,
    currentValue: 12,
    unit: 'hours',
    horizon: 'weekly',
    deadline: '2026-09-27',
    status: 'active',
    createdAt: '2026-09-21T00:00:00Z',
  },
  {
    id: 'goal-4',
    title: 'Software Engineering Intern Readiness',
    description: 'Clear Systems Programming & Algorithms requirements for technical interviews.',
    targetValue: 100,
    currentValue: 60,
    unit: '%',
    horizon: 'career',
    deadline: '2026-11-30',
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const SEED_TIME_BLOCKS: Record<string, TimeBlock[]> = {
  '2026-09-21': [
    {
      id: 'tb-20260921-1',
      date: '2026-09-21',
      slotId: 'tt-3',
      title: 'Commute & Campus Transit',
      startTime: '08:15',
      endTime: '08:45',
      durationMinutes: 30,
      type: 'commute',
      isFixed: true,
    },
    {
      id: 'tb-20260921-2',
      date: '2026-09-21',
      slotId: 'tt-1',
      subjectId: 'sub-os',
      title: 'CS 301: OS Lecture',
      startTime: '09:00',
      endTime: '10:30',
      durationMinutes: 90,
      type: 'lecture',
      isFixed: true,
    },
    {
      id: 'tb-20260921-3',
      date: '2026-09-21',
      slotId: 'tt-2',
      subjectId: 'sub-algo',
      title: 'CS 312: Algorithms Lecture',
      startTime: '11:00',
      endTime: '12:30',
      durationMinutes: 90,
      type: 'lecture',
      isFixed: true,
    },
  ],
};

export const INITIAL_SEEDED_STATE: AppState = {
  profile: SEED_PROFILE,
  semesters: SEED_SEMESTERS,
  activeSemesterId: 'sem-fall-2026',
  subjects: SEED_SUBJECTS,
  timetable: SEED_TIMETABLE,
  topics: SEED_TOPICS,
  sessions: SEED_SESSIONS,
  goals: SEED_GOALS,
  timeBlocks: SEED_TIME_BLOCKS,
  missions: {
    '2026-09-21': {
      id: 'mission-2026-09-21',
      date: '2026-09-21',
      availableMinutes: 210, // ~3.5 hours calculated capacity
      allocatedMinutes: 110,
      items: [
        {
          id: 'mi-1',
          subjectId: 'sub-os',
          topicId: 'top-os-3',
          title: 'Review Peterson Algorithm & Mutexes',
          plannedMinutes: 50,
          actualMinutes: 0,
          status: 'pending',
          scheduledTime: '14:30',
          isAIRecorded: false,
        },
        {
          id: 'mi-2',
          subjectId: 'sub-algo',
          topicId: 'top-algo-3',
          title: 'Trace Dijkstra priority queue implementation',
          plannedMinutes: 60,
          actualMinutes: 0,
          status: 'pending',
          scheduledTime: '16:00',
          isAIRecorded: false,
        },
      ],
    },
  },
};
